// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

package contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gender int32

const (
	Gender_UNKNOWN     Gender = 0
	Gender_MALE        Gender = 1
	Gender_FEMALE      Gender = 2
	Gender_UNDISCLOSED Gender = 3
)

var Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
	3: "UNDISCLOSED",
}

var Gender_value = map[string]int32{
	"UNKNOWN":     0,
	"MALE":        1,
	"FEMALE":      2,
	"UNDISCLOSED": 3,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=contracts.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_d19debeba7dea55a, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

func init() {
	proto.RegisterEnum("contracts.Gender", Gender_name, Gender_value)
	proto.RegisterType((*Person)(nil), "contracts.Person")
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor_d19debeba7dea55a) }

var fileDescriptor_d19debeba7dea55a = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xf1, 0x8b, 0x95,
	0x32, 0xb9, 0xd8, 0x02, 0x52, 0x8b, 0x8a, 0xf3, 0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x62, 0x7a, 0xaa, 0x04, 0xb3,
	0x02, 0xa3, 0x06, 0x6b, 0x10, 0x88, 0x29, 0xa4, 0xc9, 0xc5, 0x96, 0x9e, 0x9a, 0x97, 0x92, 0x5a,
	0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa8, 0x07, 0x37, 0x5b, 0xcf, 0x1d, 0x2c, 0x11,
	0x04, 0x55, 0xa0, 0x65, 0xc3, 0xc5, 0x06, 0x11, 0x11, 0xe2, 0xe6, 0x62, 0x0f, 0xf5, 0xf3, 0xf6,
	0xf3, 0x0f, 0xf7, 0x13, 0x60, 0x10, 0xe2, 0xe0, 0x62, 0xf1, 0x75, 0xf4, 0x71, 0x15, 0x60, 0x14,
	0xe2, 0xe2, 0x62, 0x73, 0x73, 0x05, 0xb3, 0x99, 0x84, 0xf8, 0xb9, 0xb8, 0x43, 0xfd, 0x5c, 0x3c,
	0x83, 0x9d, 0x7d, 0xfc, 0x83, 0x5d, 0x5d, 0x04, 0x98, 0x9d, 0xb8, 0xa3, 0x10, 0xae, 0x4e, 0x62,
	0x03, 0xfb, 0xc3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x78, 0xeb, 0x2c, 0xb2, 0xd9, 0x00, 0x00,
	0x00,
}
